# 法人ごとの出力対象を管理します。
# output: true で処理対象、false で法人ごとスキップします。
# upload_to_s3: true でS3アップロード、false でアップロードしません。
# local_csv_output: true でローカルCSVを保存、false で保存しません。
config_directory: config
facilities:
  - name: あらや滔々庵
    key: arayatotoan
    output: true
    upload_to_s3: true
    local_csv_output: true

  - name: 季さら
    key: kisara
    output: true
    upload_to_s3: true
    local_csv_output: true
