s3_info:
  bucket_name: onsen-jasper-importer-prod-data-kisara
  access_key_id: 'xxxxxxT'
  secret_access_key: 'Jxxxxxx'
  file_name: 'pms-reservations/季さら_'

csv:
  output_directory: data/tmp
  archive_directory: data/archive
  encoding: utf-8

salesforce:
  username: r.uxxx7@force.com
  password: xxxx
  security_token:
  domain: login  # or 'test' for sandbox

# Timezone used for timestamped file names and incremental windows
timezone: Asia/Tokyo

queries:
  - name: Reservations_history
    soql: |
      SELECT Id,
      Name,
      ExternalKey__c,
      NameOfFacility__c,
      FirstDay__c,
      CreatedDate,
      Status__c,
      CancellationDate__c,
      NumberOfNights__c,
      PackagePlanName__c,
      Customer__c,
      Agent__c,
      BathingTax__c
      FROM Reserve__c
    where: FirstDay__c = N_DAYS_AGO:2
    output_file: reservations_history
    write_output: false


  - name: Reservations_onhand
    soql: |
      SELECT Id,
      Name,
      ExternalKey__c,
      NameOfFacility__c,
      FirstDay__c,
      CreatedDate,
      Status__c,
      CancellationDate__c,
      NumberOfNights__c,
      PackagePlanName__c,
      Customer__c,
      Agent__c,
      BathingTax__c
      FROM Reserve__c
    where: |
      FirstDay__c >= N_DAYS_AGO:1 AND FirstDay__c <= NEXT_N_DAYS:363
    output_file: reservations_onhand
    write_output: false


  - name: Contact_history
    soql: |
      SELECT Id,
      RepeatCount__c,
      NAME,
      MailingCity,
      MailingStreet,
      MailingState,
      AgeGroup__c,
      Phone,
      Email,
      HasOptedOutOfEmail
      FROM Contact
    incremental: false
    relationship_filters:
      - source_query: Reservations_history
        source_field: Customer__c
        target_field: Id
    output_file: contacts_history
    write_output: false


  - name: Contact_onhand
    soql: |
      SELECT Id,
      RepeatCount__c,
      NAME,
      MailingCity,
      MailingStreet,
      MailingState,
      AgeGroup__c,
      Phone,
      Email,
      HasOptedOutOfEmail
      FROM Contact
    incremental: false
    relationship_filters:
      - source_query: Reservations_onhand
        source_field: Customer__c
        target_field: Id
    output_file: contacts_onhand
    write_output: false


  - name: Sales_history
    soql: |
      SELECT Id,
      Subject__c,
      Name,
      RelatedType__c,
      Amount__c,
      TaxRate__c,
      AccomTaxFlag__c,
      NumberOfCount__c,
      UnitPrice__c,
      Reserve__c
      FROM Billing__c
    incremental: false
    relationship_filters:
      - source_query: Reservations_history
        source_field: Id
        target_field: Reserve__c
    output_file: sales_history
    write_output: false


  - name: Sales_onhand
    soql: |
      SELECT Id,
      Subject__c,
      Name,
      RelatedType__c,
      Amount__c,
      TaxRate__c,
      AccomTaxFlag__c,
      NumberOfCount__c,
      UnitPrice__c,
      Reserve__c
      FROM Billing__c
    incremental: false
    relationship_filters:
      - source_query: Reservations_onhand
        source_field: Id
        target_field: Reserve__c
    output_file: sales_onhand
    write_output: false


  - name: Rooms_history
    soql: |
      SELECT Id,
      NumberOfWomen__c,
      NumberOfMen__c,
      ElementarySchoolStudentsUG__c,
      ElementarySchoolStudentsLG__c,
      InfantMealFutonNumber__c,
      InfantMeaNumber__c,
      InfantFutonNumber__c,
      InfantNumber__c,
      RoomTypeCode__c,
      RoomTypeName__c,
      GuestRoom__c,
      Reserve__c,
      PlanMaster__c
      FROM RoomReservation__c
    incremental: false
    relationship_filters:
      - source_query: Reservations_history
        source_field: Id
        target_field: Reserve__c
    output_file: rooms_history
    write_output: false


  - name: Rooms_onhand
    soql: |
      SELECT Id,
      NumberOfWomen__c,
      NumberOfMen__c,
      ElementarySchoolStudentsUG__c,
      ElementarySchoolStudentsLG__c,
      InfantMealFutonNumber__c,
      InfantMeaNumber__c,
      InfantFutonNumber__c,
      InfantNumber__c,
      RoomTypeCode__c,
      RoomTypeName__c,
      GuestRoom__c,
      Reserve__c,
      PlanMaster__c
      FROM RoomReservation__c
    incremental: false
    relationship_filters:
      - source_query: Reservations_onhand
        source_field: Id
        target_field: Reserve__c
    output_file: rooms_onhand
    write_output: false


  - name: FacilityMaster
    soql: |
      SELECT Id,
      Name
      FROM FacilityMaster__c
    incremental: false
    output_file: master_facility
    write_output: false


  - name: PlanMaster
    soql: |
      SELECT Id,
      Name
      FROM PlanMaster__c
    incremental: false
    output_file: master_plan
    write_output: false

    
  - name: RoomMaster
    soql: |
      SELECT Id,
      Name
      FROM RoomMaster__c
    incremental: false
    output_file: master_room_types
    write_output: false


combined_outputs:
  - name: Reservations_history_combined
    base_query: Reservations_history
    output_file: reservations_history
    joins:
      - source_query: Contact_history
        left_on: Customer__c
        right_on: Id
        how: left
      - source_query: Rooms_history
        left_on: Id
        right_on: Reserve__c
        how: left
        aggregate:
          group_by: Reserve__c
          fields:
            - NumberOfWomen__c
            - NumberOfMen__c
            - ElementarySchoolStudentsUG__c
            - ElementarySchoolStudentsLG__c
            - InfantMealFutonNumber__c
            - InfantMeaNumber__c
            - InfantFutonNumber__c
            - InfantNumber__c
          function: sum
          fill_value: 0


  - name: Reservations_onhand_combined
    base_query: Reservations_onhand
    output_file: reservations_onhand
    joins:
      - source_query: Contact_onhand
        left_on: Customer__c
        right_on: Id
        how: left
      - source_query: Rooms_onhand
        left_on: Id
        right_on: Reserve__c
        how: left
        aggregate:
          group_by: Reserve__c
          fields:
            - NumberOfWomen__c
            - NumberOfMen__c
            - ElementarySchoolStudentsUG__c
            - ElementarySchoolStudentsLG__c
            - InfantMealFutonNumber__c
            - InfantMeaNumber__c
            - InfantFutonNumber__c
            - InfantNumber__c
          function: sum
          fill_value: 0


  - name: Sales_history_combined
    base_query: Sales_history
    output_file: sales_history
    joins:
      - source_query: Reservations_history
        left_on: Reserve__c
        right_on: Id
        how: left


  - name: Sales_onhand_combined
    base_query: Sales_onhand
    output_file: sales_onhand
    joins:
      - source_query: Reservations_onhand
        left_on: Reserve__c
        right_on: Id
        how: left


  - name: Rooms_history_combined
    base_query: Rooms_history
    output_file: rooms_history
    joins:
      - source_query: Reservations_history
        left_on: Reserve__c
        right_on: Id
        how: left
      - source_query: PlanMaster
        left_on: PlanMaster__c
        right_on: Id
        how: left


  - name: Rooms_onhand_combined
    base_query: Rooms_onhand
    output_file: rooms_onhand
    joins:
      - source_query: Reservations_onhand
        left_on: Reserve__c
        right_on: Id
        how: left
      - source_query: PlanMaster
        left_on: PlanMaster__c
        right_on: Id
        how: left
